---
# tasks file for rsync-server

- name: rsyncd | install rsync
  become: true
  package:
    pkg: rsync
    state: present

- name: rsyncd | install rsync-daemon
  become: true
  package:
    pkg: rsync-daemon
    state: present
  when: 
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8

- name: rsyncd | create log directory
  become: true
  file:
    path: /var/log/rsyncd
    state: directory
    owner: root
    group: root
    mode: 0755

- name: rsyncd | configure shares
  become: true
  template:
    dest: /etc/rsyncd.conf
    src: etc-rsyncd.conf.j2
    mode: 0644
    owner: root
    group: root
    # No need to reload, file is re-read on each client connection.

- name: rsyncd | configure logrotate
  become: true
  template:
    backup: false
    dest: /etc/logrotate.d/rsyncd
    src: etc-logrotate.d-rsyncd.j2
    owner: root
    group: root
    mode: 0644

#- name: rsyncd | selinux allow network connect
#  become: true
#  seboolean:
#    name: rsync_export_all_ro
#    state: true
#    persistent: true
#  when: selinux_enabled

- name: rsyncd | start and enable service
  become: true
  service:
    name: rsyncd
    enabled: true
    state: started
